### ISSUE TITLE
Deleting a splay row deletes all or nothing or splay

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#100]
This issue relates to v1.3.1.  I notice we are up to v1.3.3 now, so this issue may have been corrected.  Posting this mainly to document what occurred.
While surveying our disto produced an erroneous measurement, a 100m splay shot.  On long press on the row to invoke the context menu, I select 'delete row'.  

As in the image attached, ST says it will delete 3 stations, 2 legs and 42 splays.  Of course I select cancel, and try a few more times.  same result.
So I save the file, then go through with the delete, and indeed it deletes pretty much the whole survey.  So I do not save, and reopen the file, and try again.  Same result, so I conclude that I cannot delete a single shot.

Later on in the survey I try again, and nothing happens, and still later i try, and the single splay is deleted successfully.  So a serious reliability and credibility issue there.

![CampLevallDeleteSplaySequence](https://user-images.githubusercontent.com/19825868/59970933-192db580-95c6-11e9-9f15-74d0e4ae5c9a.png)

And just looking at the statistics reported in the image.
The stats reports 2 stations, whereas in the sketch, 3 stations can be seen.
The longest leg and shortest leg reported are actually longest splay and shortest splay.  the longest and shortest legs are not reported, and probably should be (ie short report separately on splays and on legs.

Some of these issues may have been address in v1.3.3, I have not checked, except Inotice that the context menu options have changed.

**Comment by richsmith** [comment]
The deletion issues should have been fixed in 1.3.2 and 1.3.3. Surprising no one noticed before, but it must be reasonably rare that people want to delete splays that aren't the most recent one.

Can open a separate issue for the stats if you like, but I think it's a fairly minor issue.
