### ISSUE TITLE
Add Leg menu is misnamed Add Station

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#101]
In table view there is a button bottom left, a circle with a + in it.  It comes up with an 'Add Station' dialog, but asks for distance, Azimuth and Inclination.  It may be picky, but it seems to me to be a leg.  A station would have x, y and z coordinates??
So it should be titled 'Add Leg' or 'Add Leg to a new station'?
I'm comparing it to the adjacent button that is correctly titled 'Add splay'.
So for consistency the 'Add Station' dialog should be re-titled.

**Comment by richsmith** [comment]
I called it "Add station" to avoid the confusion between the terminology of "leg" v "splay". I believe in some locales "Leg" is used as a general term for splay or, well, leg (with a station). Probably won't fix this, as I think what it's doing is fairly obvious.

**Comment by CaverBruce** [comment]
Suggest that ST choose (for the sake of clear communication) and take ownership of the terminology it wants to use, and then make it clear by defining it for users to refer to.  I can understand that there is confusion where words have different meanings for some groups of people.  Distinguishing between shot, splay and leg would in the long run help with clear understanding.  ie
Shot = one measurement set (distance, bearing, clino, metadata such as disto orientation, mag and acceleration) from the disto (one beep).  It might be a splay or part of a leg.
Splay = one shot, a measurement set to a wall or feature.
Leg = one or more (usually three) shots (two-beeps) that are combined to represent are part of a survey traverse centreline.
