### ISSUE TITLE
Request ability to store survey files in cave folder

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#103]
Currently I think ST requires users to save files in a single data folder.
This means that where users are surveying many caves, and have many surveys in each cave, a simple and rigorous naming convention must be implemented by the user up front.  This is a good thing to encourage users to do, but I would suggest ST could help users a little more.

For context, I am looking at my PocketTopo folders, and for one part of one cave, I have 94 survey files, each with between 100m and 1km of survey most likely, and a total of around 15km of surveyed passage.  I have perhaps 20 other caves stored in the same device with many surveys of their own.  If I am not able to separate the caves into their own folders, and even with a rigorous hierarchical naming convention, I will be overwhelmed, as possibly would many application dialog interfaces.

Comparing to PocketTopo, where users are able to create one level of folders, one for each cave, and PT assumes each file within the folder is part of that cave.  The scenario described above is straight forward to navigate, and join surveys.
I appreciate ST survey joining paradigm is slightly different, and i like it.  However, i request the ability to have a folder for each cave's surveys.  This would greatly simplify survey management for someone who has multiple survey projects on the go at once.

**Comment by richsmith** [comment]
Yeah this would be useful. It's complicated though by the fact that Android file system access has changed a lot over different Android versions (e.g. to stop apps hoovering up all a user's data and stealing it) and I'm trying to support old hardware for surveying on. I'm still giving some thought as to the best way to proceed on this.

**Comment by tomfoord** [comment]
As you know Rich, I'm with Bruce on this. In a perfect world I would like a hierarchical folder structure where I can separate my surveys by country, area, cave, etc. However I'd settle for a simple, flat structure where each cave lives in a folder of its own.

**Comment by CaverBruce** [comment]
https://github.com/richsmith/sexytopo/commit/d892d3acc567452caf40016624f728c318b0e26f

**Comment by richsmith** [comment]
@CaverBruce yes, this is what I'm working on. I think the only way to comply with Android's stupid new requirements is to get the user to choose where all the files are. It's a biiiig change, though, and I still haven't quite figured out how survey joining is going to work.

**Comment by CaverBruce** [comment]
@richsmith Appreciate all the work you're putting into this and ST in general. Can only commiserate vaguely on the trials that OS developers put their clients and users through.
Maybe a constraint can be a flattish folder structure , one per contiguous cave passage, and only surveys in the same folder/contiguous passage can be joined (it is a field data collection app after all, not for final model, maps, representations).  Of course I don't have a handle on what you're dealing with, so take my comments with a grain of salt...

**Comment by richsmith** [comment]
Latest changes (in beta) make users have to choose where to put files, so you can organise how you like. At some point I'll add something to understand hierarchical surveys (surveys nested within folders / directories) with proper tools to manage.
