### ISSUE TITLE
Statistics need to report separately on splays, legs and separately on this survey, all linked surveys 

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#105]
Refer to #100 for background and some images.
The statistics (menu >Tools>Stats) reports only on the cumulative length of all linked surveys and reports shots, merging splay statistics with leg statistics, but calling them legs (ie incorrectly reporting as longest leg and shortest leg).

There should be two sections to the statistics report, the first being for the current survey (trip) only.  It could be similar to the existing report, but with the splay and leg length reporting resolved.
The second section should be for cumulative statistics including all linked surveys/trips.  Personally I am only interested in total length and total vertical range for cumulative statistics, but it could include the other fields as well.

**Comment by richsmith** [comment]
Fixed ready for 3.4.1.
