### ISSUE TITLE
Import of PocketTopo Therion .txt export files fails with 'Error: length=1; index=n'

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#106]
See attached files. When attempting to import these I get either 
"Error: length=1; index=1"
or
"Error: length=1; index=2"

[WUG-2016-08-20-1-BigRiftEastPot-th.txt](https://github.com/richsmith/sexytopo/files/3454029/WUG-2016-08-20-1-BigRiftEastPot-th.txt)
[WUG-2016-08-20-2-HoleBeneathTightPitchHead-th.txt](https://github.com/richsmith/sexytopo/files/3454030/WUG-2016-08-20-2-HoleBeneathTightPitchHead-th.txt)
[WUG-2016-08-22-2-LeftFork-th.txt](https://github.com/richsmith/sexytopo/files/3454031/WUG-2016-08-22-2-LeftFork-th.txt)
[WUG-2016-08-23-1-ChutneyChambers-th.txt](https://github.com/richsmith/sexytopo/files/3454032/WUG-2016-08-23-1-ChutneyChambers-th.txt)
[WUG-2016-08-24-1-RoadToHell-th.txt](https://github.com/richsmith/sexytopo/files/3454033/WUG-2016-08-24-1-RoadToHell-th.txt)
[WUG-2016-08-24-2-ForlornHopeAndMudlicker-th.txt](https://github.com/richsmith/sexytopo/files/3454034/WUG-2016-08-24-2-ForlornHopeAndMudlicker-th.txt)
[WUG-2016-08-25-1-RebornHope-th.txt](https://github.com/richsmith/sexytopo/files/3454035/WUG-2016-08-25-1-RebornHope-th.txt)
[WUG-2017-08-25-1-BeggarsReverse-th.txt](https://github.com/richsmith/sexytopo/files/3454036/WUG-2017-08-25-1-BeggarsReverse-th.txt)
[WUG-2017-08-26-1-ABigDayOut-th.txt](https://github.com/richsmith/sexytopo/files/3454037/WUG-2017-08-26-1-ABigDayOut-th.txt)
[WUG-2017-08-26-2-Frexit-th.txt](https://github.com/richsmith/sexytopo/files/3454038/WUG-2017-08-26-2-Frexit-th.txt)
[WUG-2017-08-29-DeepSludgeContinued-th.txt](https://github.com/richsmith/sexytopo/files/3454039/WUG-2017-08-29-DeepSludgeContinued-th.txt)
[WUG-2017-09-05-1-Armageddon.th.txt](https://github.com/richsmith/sexytopo/files/3454040/WUG-2017-09-05-1-Armageddon.th.txt)
[WUG-2017-09-06-1-Showadiwadiland.th.txt](https://github.com/richsmith/sexytopo/files/3454041/WUG-2017-09-06-1-Showadiwadiland.th.txt)
[WUG-2018-09-05-1-UphillGardeners-th.txt](https://github.com/richsmith/sexytopo/files/3454042/WUG-2018-09-05-1-UphillGardeners-th.txt)
[WUG-2018-09-06-1-PassportControl-th.txt](https://github.com/richsmith/sexytopo/files/3454043/WUG-2018-09-06-1-PassportControl-th.txt)
[WUG-2018-09-16-1-MainEntPermanentStation-th.txt](https://github.com/richsmith/sexytopo/files/3454044/WUG-2018-09-16-1-MainEntPermanentStation-th.txt)
[WUG-2018-09-16-2-2ndEntPermanentStation-th.txt](https://github.com/richsmith/sexytopo/files/3454045/WUG-2018-09-16-2-2ndEntPermanentStation-th.txt)
[WUG-2016-08-16-1-SideSeriesBelow2ndPitch-th.txt](https://github.com/richsmith/sexytopo/files/3454046/WUG-2016-08-16-1-SideSeriesBelow2ndPitch-th.txt)
[WUG-2016-08-16-2-2ndEntrance-th.txt](https://github.com/richsmith/sexytopo/files/3454047/WUG-2016-08-16-2-2ndEntrance-th.txt)

**Comment by richsmith** [comment]
It was getting confused with trip data (which I've so far been too lazy to import properly). Should be fixed, but I haven't checked all the files.
