### ISSUE TITLE
Import of PocketTopo Therion .txt export files sometimes places first station in wrong place on the drawings

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#108]
See attached PocketTopo Therion .txt export files.
When I import these into SexyTopo it places the first station (and therefore all subsequent stations) in the wrong place on the drawings. I think it may actually be placing the 1st station on the location of the 2nd station.

[WUG-2015-08-23-2-100mPitch-th.txt](https://github.com/richsmith/sexytopo/files/3454084/WUG-2015-08-23-2-100mPitch-th.txt)
[WUG-2015-08-25-2-Meander-th.txt](https://github.com/richsmith/sexytopo/files/3454085/WUG-2015-08-25-2-Meander-th.txt)
[WUG-2015-08-27-2-FinalPitch-th.txt](https://github.com/richsmith/sexytopo/files/3454086/WUG-2015-08-27-2-FinalPitch-th.txt)

**Comment by richsmith** [comment]
Yep, correct. Think I've fixed this!
