### ISSUE TITLE
Open Survey menu lists surveys in no particular order

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#109]
The Open Survey menu lists all of my surveys which I imported from PocketTopo, but they are seemingly in no logical order (certainly not alphabetical, or by date). This makes it difficult to find the survey I'm looking for.

**Comment by richsmith** [comment]
Which would you prefer, date or alphabetical?

**Comment by tomfoord** [comment]
My preference is alphabetical. This would work nicely with my file naming
convention which starts with cave name followed by date in yyyy-mm-dd
format.

**Comment by richsmith** [comment]
Happily that's super-easy. Added to the next version.
