### ISSUE TITLE
SexyTopo crashed when renaming station

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#110]
I've managed to crash SexyTopo while renaming a station.

Running SexyTopo v1.3.5 on a Samsung Note 3

I was using test data generated via the 'Generate Test Survey' option in the Tools menu. 

I attempted to rename station 15 as 201. This resulted in the application hanging for a few minutes, and then eventually I got the message:
"SexyTopo isn't responding. Do you want to close it?"

**Comment by richsmith** [comment]
Thanks. I don't think I've received an error report though. Have you connected your device to Wifi? It should automatically upload a stack trace of the error.

**Comment by tomfoord** [comment]
Yes I was connected to wifi at the time.

Annoyingly I haven't been able to reproduce the error. Seems like it was a
random one-off occurrence.

**Comment by richsmith** [comment]
I've got one error report in the last few days but it appears to be from a
huawei device? If that's yours, it's a bit odd. I can't work out how it
could have happened, but I stop it crashing if it happens again.

**Comment by tomfoord** [comment]
Nope that's not mine, I was using a Note 3. Will see if I can make it
happen again tonight.

**Comment by richsmith** [comment]
Think I've found it. No stack trace as it's an ANR. I can't really tell what's happened. Looks like something happened in Android internals when creating a new row syncing the table with the survey (if you care about the details!) A tricky one to fix if you can't recreate it.

**Comment by richsmith** [comment]
Going to close this as a one-off problem. Please reopen if it starts happening again.
