### ISSUE TITLE
Keyboard launch when renaming station

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#112]
Minor gripe: When I select Rename Station, initially no keyboard appears even though the cursor is present at the start of the Edit Name field. The keyboard only appears if I tap elsewhere in the field. This is slightly irritating if all I want to do is prefix the station name, as it requires me to move the cursor elsewhere and then move it back again in order to launch the keyboard.

**Comment by richsmith** [comment]
Very easy to fix, so fixed.
