### ISSUE TITLE
Therion xvi export depends on locale

### ISSUE THREAD

**Issue by mzbenoit** [richsmith/sexytopo#113]
When exporting to Therion format, "xvi" file depends on locale. It should not.

exemple with fr_FR locale :
`set XVIsketchlines {
	 {BLACK -401,57 492,13 -425,20 468,50 -437,01 433,07 -437,01 405,51} }
`
It should be : 
`set XVIsketchlines {
	 {BLACK -401.57 492.13 -425.20 468.50 -437.01 433.07 -437.01 405.51} }
`
without comma but dot

**Comment by richsmith** [comment]
Thanks for the bug report! I'll try to fix this weekend.

Rich

**Comment by richsmith** [comment]
Should be fixed in new version
