### ISSUE TITLE
Maximum delta for distance and angle

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#116]
I presume the default distribution comes with delta values that do not match the distoX2 values of 0.05m and 1.7 degrees.  Assuming this is the case, it can cause confusion where either;
- The disto operator assumes that a leg has not been registered, because the disto has not double-beeped, and so keeps on generating multiple legs that will need to be deleted in ST, if the ST operator even notices, or
- The disto operator assumes that a leg has been registered because the disto double-beeps, but it has not been registered by ST, and so the 'leg' is instead recorded as splays.  A related issue, as far as i can tell, one cannot convert three splays that should be a single leg into a single leg, it instead can be forced to three new legs to three new stations.

I suggest that the default delta values that ST ships with are set to exactly match the deltas built in to the distoX2
See also #116 #102 #101 #92 #48 #73 #46

**Comment by richsmith** [comment]
Huh, I thought I was using the default values for some reason. I assume you are correct. Fixed.
