### ISSUE TITLE
No way to upload or save calibration

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#119]
Thought I'd commit to using ST for a day's solo surveys, leaving behind the windows device and PocketTopo.  Calibration of the disto didn't go so well, firstly the pre-calibration check was a pain (another issue), and then there was no way to upload or save the calibration.
I see looking on the play store images there should be an upload and save button below the calibration assessment.  As you can see in the screenshots, i did not get that, 
Also despite clicking stop calibration, the start calibration never became active again (although the disto state changed from normal to cal and back OK.

![2019_09_01_14 00 08](https://user-images.githubusercontent.com/19825868/64099657-eec65880-cdbd-11e9-8cab-8852127615ed.jpg)
![2019_09_01_14 02 51](https://user-images.githubusercontent.com/19825868/64099658-eec65880-cdbd-11e9-9499-f5188e8c1d40.jpg)

![2019_09_01_14 07 48](https://user-images.githubusercontent.com/19825868/64099655-ee2dc200-cdbd-11e9-9dfb-410ef3479ea3.jpg)
![2019_09_01_14 11 31](https://user-images.githubusercontent.com/19825868/64099656-eec65880-cdbd-11e9-972d-81990a2ef272.jpg)

**Comment by richsmith** [comment]
This issue has been reported. It looks like on some devices the resolution forces the bottom row of buttons offscreen. Annoying...

The screenshot is interesting - maybe it's the on-screen buttons at the bottom that are the problem. Something I need to fix.

**Comment by CaverBruce** [comment]
OK, checked this on another device.  Samsung S8 does include the buttons at the bottom of the screen, but i don't take this one caving!
Nokia 2 does not have the buttons at the bottom of the screen, and there seems to be no way to scroll down to them.

**Comment by richsmith** [comment]
I recommend a 2nd-hand Galaxy Note - e.g. a 3 or a 4.

Anyway, I think I've fixed this in the upcoming version. Please reopen if I haven't.

**Comment by CaverBruce** [comment]
Thanks for the tip on a reasonable device - I'm generally unimpressed with Android displays as a drawing input modality, i may see if i can pick one up.

**Comment by CaverBruce** [comment]
Here is a screenshot from Nokia II.  Some clipping of the data, but at least all of the buttons are visible.  Thanks

![2019_09_04_07 49 47](https://user-images.githubusercontent.com/19825868/64205668-a48fc500-ceec-11e9-9fd7-a63e2e2a214c.jpg)
