### ISSUE TITLE
Calibration sequence prompts

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#121]
I like the ST prompts for calibration sequence, to help keep one focused.  However I find the order chosen (front right back left) rational, but unnatural.  For me front back left right is so much easier to resolve.  ie, front back uses a single pair of 'stations', then left right uses another pair of stations, etc.  FRBL requires twice as much changing.
Suggest changing the suggested sequence, or making it a user setting.

**Comment by richsmith** [comment]
It annoys me that the back-right follows forward-right. I was thinking of turning clockwise, but in fact I find I turn around. Have made both changes.

**Comment by CaverBruce** [comment]
Nice, much better in v1.3.11
