### ISSUE TITLE
calibration checks are not easily implemented

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#122]
As recommended by Beat, I tend to do a distoX calibration check before most surveys, and i save the shots in the survey file attached to the first (or any) survey station (they could be saved elsewhere, but i like to have them attached to the data they pertain to).
I expand on Beats recommendation, and do 4 shots (saved as splays) in each direction (face up, right, down, left).  Elsewhere I process these in a spreadsheet to track any calibration adjustments to apply to the Therion file.
To get started, one needs to do 4 shots saved as splays.  This is one scenario where #102 point 2 becomes important.  With ST, as soon as you have three similar shots, it creates a leg and a new station.  Rather than just doing a fourth shot, and making appropriate edits to the from and to stations to turn them all back to splays (which is very easily done with PocketTopo), you have to delete the erroneous leg, take two calibration check splays, make a random shot, then take two more calibration check splays, then hope in the non-chronological table you can find the random shot and delete it.
I find it easier to have simple uncomplicated process for taking shots, and make any adjustments in the booking process (which is my thinking behind #102

**Comment by richsmith** [comment]
Not a separate issue

**Comment by CaverBruce** [comment]
Is it possible to disable in ST the 'three shots' turns three similar splays into a leg?  If not this is a live issue.  Are you taking this as related to #123 ?

**Comment by richsmith** [comment]
Thought we already had an issue for this. Maybe not...

**Comment by richsmith** [comment]
Input Mode -> Calibration check mode to turn off leg promotion? Or what?

**Comment by richsmith** [comment]
OK, looks like that was easy. Added. Might be nice to add a comment saying it was a calibration check, but that's trickier.
