### ISSUE TITLE
delta 0 causes loss of downloaded shot data

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#123]
I tried setting the bearing delta to 0 to disable the 3 shot in a row creates a leg behaviour (see #102 )
What it did was to download data from the disto (as per normal) but then it did not show up in the data table or the sketch windows - it was just gone.  I tried this for several shots a number of times.  Nothing, data transfers from the disto and then is gone.  One odd thing i should have explored, but did not realize at the time - there was no active station - don't know how that happened - could have been because there was only one station and one splay as it was the start of the survey trip.  I should have tried making the station active to see if that fixed things.

**Comment by richsmith** [comment]
It should be impossible in theory for there to be no active station even if the display hasn't picked it up. I'll check this.

**Comment by richsmith** [comment]
I've fixed some problems with the active station being lost in the latest version. Hopefully this issue is now fixed.
