### ISSUE TITLE
Set active station from sketch window does not set the active station in the table

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#124]
Sometimes when I set an active station in the sketch window, and then switch directly to the data table, the active station indicator (yellow) remains on the original active station.
Not wanting to mess up my data, I always set the active station in the table as well (to match the station in the sketch window).
Not sure what would happen if i did not do that, possibly the data table is just slow to update and all would be well.

**Comment by richsmith** [comment]
It's an artefact of the performance improvements I added recently. The data are fine, it's the table not realising it needs to update. I've just fixed it.
