### ISSUE TITLE
Start new survey - wierd naming of stations

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#125]
When starting a new survey at station 33 (although it could have been 34 as I cannot open the actual file) the new survey starts at station 3.4

Not really a problem, but I did not notice it was not using counting numbers and just left it. It would be far better to just start at 0 or 1 on a new survey.

I and my team find the #.# format very confusing and it just leads to mistakes

**Comment by richsmith** [comment]
I don't believe there's any code left that uses the #.# format. New surveys are started with the same name as the station they are branched from. Sure it wasn't an old survey with station 3.4? I think it makes sense to keep the same number. If you stop halfway down a passage, you want to continue with the same numbering scheme rather than start from 1.

**Comment by AndrewAkinson** [comment]
The survey did have some #.# on the first leg, the calibration check, which
I did first. But the station I took it from was 33.
So it found 1.1, 1.2  at the start, but then chose 3.4.? Anyway as i said
not that important, really just recording it for completion in case it
impinges on something else in the future.

Agreed it should use the same format as previous

Andrew

**Comment by CaverBruce** [comment]
Did a quick check with v1.3.10
All seems well, the next station inherits the numbering scheme of the previous station, whether it be 1-2-3, 1.1-1.2-1.3, or 1a-2a-3a.
I haven't had any troubles of this type in recent versions.

**Comment by richsmith** [comment]
No idea how this could have happened then. If you try again and get the same issue you can send me the file if you like and I'll have a look. Otherwise, closing for now.
