### ISSUE TITLE
Therion thconfig export has quotation marks around file name

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#127]
This is more of a comment than an issue, and it may be operating system dependent.
The thconfig files created by ST contain export statements that have quotation marks around the output file name.
eg
`export map -proj plan -layout local -o "ME-80-AngelicaTopSurface-plan.pdf"`
This could be considered a 'safe' approach, however it is unnecessary if the filename does not contain any spaces.
I would prefer it to not have quotation marks, but I concede this is just a personal preference to avoid unnecessary characters, and that others may not agree or care.

**Comment by CaverBruce** [comment]
Same applies to statements in .th and .th2 files created by ST

**Comment by richsmith** [comment]
I'm going to keep the quotation marks. Can't stop users putting spaces in filenames now it's in their hands but hopefully SexyTopo handles the spaces OK.
