### ISSUE TITLE
Created with SexyTopo

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#128]
The exported Therion data th file starts out 
```
encoding utf-8
# created with SexyTopo
```
This is a good thing.  It would be even better if it stamped the version of SexyTopo that exported the file.
To be pedantic, if SexyTopo was updated between collecting the data and making the export, the two versions and dates could be reported as well.  But that might be over the top.
Making either of these updates would be invaluable for tracking bugs, or having confidence in the providence of older data, when viewed from some future date.

**Comment by richsmith** [comment]
Seems reasonable, have added it. Will be in the next version (chronological legs update).
