### ISSUE TITLE
No text size control setting for sketch window scalebar and filename

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#129]
I have ST installed on a few general-use type phones (Samsung and Nokia), and the text size of the scalebar label and file name identifier is fine (well, maybe a little small for my old poorly focused 'caving' glasses).  Recently installed ST on a Samsung Note 3, and the same text is way too small.  I presume if I reduce the device display resolution, this will improve the situation.  
However none of the sketch display size settings seem to affect the size of this text.  I suggest that this be added as either a stand alone setting, or linked to some proportion of the station label size.

**Comment by richsmith** [comment]
Text scaling has been improved in the latest version; hopefully fixed now.
