### ISSUE TITLE
Data format seems to depend on locale

### ISSUE THREAD

**Issue by fpetrot** [richsmith/sexytopo#13]
Hello Rich, and many thanks for your efforts !
I have an issue re-reading data from a saved file in sexytopo, and it seems to be related to the (french) local (if such a notion exists in Android)  of my phone, as it says (in a toast) "Error:invalid double:2,50". Please note the comma, as used in France for floating point (even called "nombre à virgule", virgule being comma in French) instead of the anglo-saxon dot.
So it seems that the routine that save the data uses the locale and the one that reads them back just ignores the local.

**Comment by richsmith** [comment]
Thanks for the bug report! I believe I've now fixed this so it should work in the next release.
