### ISSUE TITLE
Huawei P30 slows down and becomes unstable around 100 legs

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#134]
I have a crash test dummy who is using a Huawei P30 to survey caves.  He says it becomes unstable and crashes frequently after about 100 legs.  He suspects it might be due to insufficient RAM.  Not sure if it is a 6 GB or 8 GB model.
The work around he adopts is to create a new survey file, and link it to the first.  He does not have any problem linking many files, but would prefer not to have to adopt this approach after so few legs.

**Comment by richsmith** [comment]
The new version will have significant performance improvements and fix a crash problem so going to close this. More performance improvements will come later.
