### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ninelima** [richsmith/sexytopo#138]
Revision: 21c6d0e9c04f2e7125f6886e18f7dc8aa71979e6

</h/src/sexytopo>./gradlew build
> Task :app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:lint'.
> No value has been specified for property 'lintClassPath'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by richsmith** [comment]
Sorry, looks like I missed this issue the first time around. Is this still a problem? It builds fine for me and other people.

**Comment by ninelima** [comment]
Just tested with the current version. These are the results.

----------------
> Task :app:lint
Ran lint on variant debug: 407 issues found
Ran lint on variant release: 406 issues found
Wrote HTML report to file:///data/src/sexytopo/app/build/reports/lint-results.html
Wrote XML report to file:///data/src/sexytopo/app/build/reports/lint-results.xml

> Task :app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:

  /data/src/sexytopo/app/src/main/java/org/hwyl/sexytopo/control/io/Util.java:246: Error: Field requires API level 19 (current min is 18): android.os.Environment#DIRECTORY_DOCUMENTS [NewApi]
                      Environment.DIRECTORY_DOCUMENTS), "SexyTopo");
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 55s
62 actionable tasks: 62 executed
player@topsy:~/src/sexytopo$

**Comment by richsmith** [comment]
Can't replicate this
