### ISSUE TITLE
Export to Pocket Topo

### ISSUE THREAD

**Issue by WettiCaver** [richsmith/sexytopo#139]
Hi :-)
What's the easiest way to export to Pocket Topo? Actually I'm using Visual Topo but as there exists no direct export to Visual Topo I was planing on exporting from Sexy Topo to Pocket Topo and then from Pocket Topo to Visual Topo :-) I know that there exists an export to Pocket Topo, this creates a .txt file - but Pocket Topo keeps telling me that it's unable to open that file. What should I do?

All the best,
Wetti

**Comment by theSCRAG** [comment]
Does VisualTopo only support PocketTopo .top files? 
Maybe give cSurvey a try. It could import PocketTopo export files and should also work support VisualTopo

**Comment by richsmith** [comment]
Closing as duplicate of #115
