### ISSUE TITLE
Bluetooth pairing: Need to enter password everytime

### ISSUE THREAD

**Issue by simnic** [richsmith/sexytopo#14]
On every connection or data pull from device. 
Password dialog for bluetooth pin is shown.

Tesed on:
**DistoX2 (V2.4)**

**OnePlus X**
- Bluetooth: v4.0, A2DP
- OS    Android: v5.1.1 (Lollipop)

**Samsung S7710 Galaxy Xcover2**
- Bluetooth: v4.0, A2DP
- OS    Android:  v4.1.2 (Jelly Bean)

**Comment by chillycharly** [comment]
Same issue with a DistoX2 (V2.4) and a Kazam Thunder2 45L (Android 4.3).

On detection, the message "Device detected but is not a DistoX" is displayed. Even so, data transfer works for a single data transfer.

**Comment by richsmith** [comment]
Thanks for the detailed bug reports. I'm expecting to get a new DistoX shortly so hopefully should be able to replicate the problem and fix it.

**Comment by richsmith** [comment]
This may be fixed after a few changes to the communication code. It would be useful if anyone could check to see if this is still a problem in the most recent version.

**Comment by AndrewAkinson** [comment]
I'm having the initially reported issue with a 1.0.11 on an Amazon fire 7 (7th Generation) FIre OS 5.4.0.1 DistoX 2.4
This is not occurring on Hudl 2 running Android 5.1 (however the sceen is too poor for doing a survey on, but pretty sure that is not SexyTopos fault)
Not sure how to get the Bluetooth version, sorry

**Comment by richsmith** [comment]
I'm going to have to borrow one of these devices if I'm going to get to the bottom of this one.

**Comment by AndrewAkinson** [comment]
I'll try to remember to bring the amazon one to HE for you to borrow

**Comment by richsmith** [comment]
Thanks for the lend. Unfortunately though the data connection on the Fire
seems to be working fine with my Disto so far. It seemed a bit hesitant to
pair, but after that seems fine. I believe my Disto is version 2.5 but I
don't know whether or how the firmware version would affect this issue.
Maybe a firmware upgrade would fix the issue? I don't know.

**Comment by AndrewAkinson** [comment]
Yep the distoX I'm using is version 2.4, but works fine with my phone and other tablet, so assumed it was Sexytopo. If you can get it back to me, I will try firmware 2.5. I have a few DistoX so can leave one in 2.4 to do a more checking, if that helps.

**Comment by richsmith** [comment]
I've borrowed two older Distos but still haven't managed to reproduce this. I've rewritten some of the Bluetooth code to be more sensible so hopefully that has fixed it (again)! Please let me know if this is still happening.

**Comment by chillycharly** [comment]
Hi Rich,

I’ll test it ASAP.
Thanks for investigating the problem.

**Comment by richsmith** [comment]
I haven't heard any complaints about this for over a year so I assume it's no longer a problem!
