### ISSUE TITLE
Files are not saved/exported

### ISSUE THREAD

**Issue by guillaumechardin** [richsmith/sexytopo#140]
Hello,
I just try to use sexy topo, installed from google play store.
When I save the file and export data, i am not able to find the exported file (tested with all export format).

I've searched on sd card and local storage.

I tried to remove/reinstall app (and by the way lost my test surveys).

What is the export folder path, what is the default storage location of the app ?

GC.

**Comment by richsmith** [comment]
I assume this is OK, so I'm going to close.

I also fixed a bug whereby some surveys were not being saved correctly in the latest version of Android, which should be released later today.
