### ISSUE TITLE
SVG output different line size than shown in the app. 

### ISSUE THREAD

**Issue by adam-sampson** [richsmith/sexytopo#152]
I made a test map in bluestacks and it looked nice with line widths of 1. When i exported the SVG to windows the line widths were were 3 in the exported file. I'm not sure why one showed on the screen and was different in the export.

**Comment by richsmith** [comment]
The SVG output is a bit basic at this point and something that needs a bit of work in the future. I'm not sure how line width works in SVG but sounds like something that would be easy enough to update.  Thanks for the suggestion.

**Comment by richsmith** [comment]
Done in forthcoming release. Option in settings.
