### ISSUE TITLE
Splays can be set to active station

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#161]
I'm not sure if this is a bug or if it has some useful purpose.
All splay stations/shots can be made the active station.

![image](https://user-images.githubusercontent.com/19825868/130339676-6d435d44-3c46-4dc3-820e-900bc282592e.png)
![image](https://user-images.githubusercontent.com/19825868/130339685-8e8edad1-1197-4192-914e-50ef71001ddf.png)

**Comment by richsmith** [comment]
Definitely a bug! Has a guard against in the newest beta version but table needs to be rethought at some point.
