### ISSUE TITLE
Delete current survey dialog could be clearer

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#162]
The delete current survey does not identify the file that will be deleted.  Well yes, it is the 'current one', and if you are in a sketching screen, the survey name will be in the bottom of the screen, but greyed out and in my case too small to be legible.  If you are in data table screen, then there is no indication of the name of the survey that will be deleted.
![image](https://user-images.githubusercontent.com/19825868/130373614-022d1900-3570-4a5b-81b5-0005642d8540.png)

I request that the delete survey clearly identify the name of the survey that will be deleted.

**Comment by richsmith** [comment]
Added to next version
