### ISSUE TITLE
calibration file extension *.cal suggested

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#163]
The default behaviour when saving a calibration creates a file without an extension.
This is probably fine if you have one survey data collecting device, use only ST, leave the file in the local 'Calibrations' folder, and include an abbreviation of 'calibrate' in the file name.
If you have multiple devices and or use multiple applications (ST, PocketTopo, TopoDroid) and store calibration files centrally, it can be helpful to to have the application append a consistent extension to the filename.
I suggest *.cal for calibration files.

**Comment by richsmith** [comment]
No longer an issue because the user has to select the filename.
