### ISSUE TITLE
Fore-/Backsights old setting doesn't work

### ISSUE THREAD

**Issue by tarquinwj** [richsmith/sexytopo#169]
Menu - Input mode - Fore-/Backsights

The documentation des not say exactly how this should work, and needs to say that a single splay is required in each direction.

Settings - Automatic backsight promotion used to do the same thing, but is no longer needed (and does not do anything). It should be removed.

Android 11
SexyTopo 1.6.1

**Comment by richsmith** [comment]
Setting removed for next version
