### ISSUE TITLE
Crash in emulator when placing cross section a long way from the station

### ISSUE THREAD

**Issue by tarquinwj** [richsmith/sexytopo#174]
Bluestacks (maybe it's a Bluestacks problem, I cannot repro on a proper device, maybe it only happens on lower end devices).
Run SexyTopo. Generate a test survey.
New cross section on station 5.
Zoom out a long way then tap far outside the cave's area.
Crash.

SexyTopo 1.6.1

**Comment by richsmith** [comment]
Can't replicate
