### ISSUE TITLE
The 3 readings become  one with Therion (and probably other) Exports

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#18]
When 3 readings are taken and become a leg, if you try to edit them, it appears as a single reading, also on the export only 1 reading is exported.
This should not happen, as it is also possible to take 1 reading and make it into a leg, it is important to be able to distinguish the difference, is it is likely that the multiple reading leg is less likely a blunder than the single reading, survex is in the process of taking account of this, I believe.
It is also important as at times, say for avens, the user might have overriden a set of legs that did not become a leg automatically, these are more varied and by just having the export, this cannot be ascertained.
The DistoX also records its rotation when taking a reading, this would be useful to be stored, as a leg with 3 readings with the same orientation is not as likely to be correct as a leg with at least 2 orientations. (I wonder if this should be a different issue)

**Comment by richsmith** [comment]
There are various advantages in the code and UI to treating the three readings as one measurement. Would adding a comment to the leg saying how the leg was produced suffice?

**Comment by AndrewAkinson** [comment]
I think at a bear minimum you need to have the 3 (or whatever number used)
legs as a comment, this is what topParser does, as at the time I wrote it
survex could not deal with é readings.
I think only seeing the one line slightly holder in the UI is good. But
essentially the number one rule for surveying is record what you do, in the
way you do it. It really helps in years to come...

Andrew

On 14 Sep 2017 1:20 pm, "Rich Smith" <notifications@github.com> wrote:

There are various advantages in the code and UI to treating the three
readings as one measurement. Would adding a comment to the leg saying how
the leg was produced suffice?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/richsmith/sexytopo/issues/18#issuecomment-329464726>,
or mute the thread

**Comment by richsmith** [comment]
SexyTopo now keeps a record of the readings used to create a leg. No way of seeing this in the UI for now (can be a separate issue if required) but does output it as a comment in the saved file.

**Comment by AndrewAkinson** [comment]
Excellent, thank you, just got the new release, testing will have to wait until Mexico, nothing like are real field test...
