### ISSUE TITLE
Major limitation; unable to import or recover backups on Android 11

### ISSUE THREAD

**Issue by tarquinwj** [richsmith/sexytopo#180]
Android 11 does not allow apps to access the files created by other apps, even if the app has permission to access media and files.
If you try migrating from one phone to another, you cannot access the surveys that you copied, so all your old surveys are unavailable. It is also impossible to use menu - File - Import on those same devices.

We came up with several suggestions for how to fix this:
1. Access to all files permission. This stopped working in Android 11's most recent update.
2. Register with google as a trusted app that is allowed to access all files. unlikely to get permission for this.
3. Ask the system for access to a folder tree, which fires up the Android folder chooser. The user could then choose the folder.
4. Fake it. Rename the files to .jpg so they are treated as media, so SexyTopo can access them. Not a nice solution.

Android 11
SexyTopo 1.6.1

**Comment by richsmith** [comment]
The other option is to let the user manage the file opening each time, but that has its own issues and would require a significant rewrite. In the short term I'm going to try to get option 3 working.

**Comment by richsmith** [comment]
This has been fixed in the latest release - user has to choose files / directory themselves.

**Comment by tarquinwj** [comment]
\o/

Thank you!
