### ISSUE TITLE
Older versions of Android show rendering artifacts while drawing

### ISSUE THREAD

**Issue by tarquinwj** [richsmith/sexytopo#181]
I doubt this is considered important, but since Dan's performance fixes (1.6), we have seen rendering artifacts showing up on older versions of Android. They appear while you are drawing whenever you move the stylus slowly, and most of them disappear when you stop drawing. However, sometimes a few of them remain after you stop drawing.

The issue appears like lines pointing towards the top left corner of the screen, matching the colour you are drawing in.

![20211123_182919-1](https://user-images.githubusercontent.com/37445545/143239036-dd04231d-a8de-4c9a-a736-776c1c28a395.jpg)

Possibly a fault with the device's graphics drivers or hardware acceleration.

Samsung Galaxy Note 4.
Android 7.

**Comment by richsmith** [comment]
Haven't had any other reports about this so closing as isolated issue
