### ISSUE TITLE
Force the user to accept the storage access permission

### ISSUE THREAD

**Issue by romainreignier** [richsmith/sexytopo#188]
To follow the discussion of https://github.com/richsmith/sexytopo/issues/186

One of my colleague told me that he could not access his Surveys while during the survey, the save button worked.
It somehow happened that the ***Storage** permission was not enabled for SexyTopo. He is using Android 7.
I have managed to reproduce it on the Android Studio simulator.
It seems that the data is still available.

I think we should force the user to enable the storage permission by checking explicitly on startup and don't proceed if the permission is not granted

https://user-images.githubusercontent.com/8845664/221143713-49925135-9f2f-44da-9275-ebab1edba4f9.mp4

**Comment by richsmith** [comment]
It makes sense, but the file handling is changing in the next version anyway so I think file permissions will not be necessary (user has to select the files themselves). With other permissions, hopefully they should be more obvious.
