### ISSUE TITLE
Edit stations with the same name (or override to make into a leg)

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#19]
When editing a station labelled as a - if you select the bottom one to try to make it into a number, to make it into a leg, the first in the list of - is edited, not the one highlighted or active station.
One significance of this is that you cannot override a splay to become a leg. This can be important to show Avens etc.
Sexytopo 1.0.11

**Comment by richsmith** [comment]
The expected way to manually upgrade a splay to a leg is to long-click and select "force new station".

Renaming a station from "-" probably shouldn't be allowed. I'll take a look.

**Comment by AndrewAkinson** [comment]
On 14 Sep 2017 1:24 pm, "Rich Smith" <notifications@github.com> wrote:

The expected way to manually upgrade a splay to a leg is to long-click and
select "force new station".


Hmm, I'd tried that. It is more subtle, probably even counter intuitive.
Long click on a station you only get, edit, delete, rename, set as active.
To turn it into a leg, the long click has to be on a measurement to get the
force station.

Renaming a station from "-" probably shouldn't be allowed. I'll take a look.


Yep agree, especially as it gives weird results.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/richsmith/sexytopo/issues/19#issuecomment-329465618>,
or mute the thread

**Comment by richsmith** [comment]
Renaming the end of a splay has now been disallowed.
