### ISSUE TITLE
Orientation setting appears to be ineffective

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#195]
Regardless the  orientation setting chosen (auto, portrait, landscape) the behaviour is that SexyTopo always follows the device orientation setting (which happens to be auto).  ie The SexyTopo setting appears to be completely ineffective.  I have not checked other device orientation settings.

While I prefer 'auto' for almost all apps, I have this idea that I would prefer SexyTopo to stay with the orientation I set, because in a cave I regularly draw while contorting at odd angles, and having the app flip in the middle of a drawing will result in a mis-draw and add to frustration.

As Andrew mentions in #47, I have the feeling that being able to deliberately switch orientation at short notice might be an advantage. 

SexyTopo 1.7.0 beta3
Android 10

**Comment by richsmith** [comment]
Ah yes, can reproduce on newer devices. Still seems to work on older devices. Looks like Google has made doing this more complicated. On the list to fix...

**Comment by richsmith** [comment]
This is fixed for the next release
