### ISSUE TITLE
Incorrect way to reverse a leg

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#20]
As stated previously a survey program should record what a survey actual does.

So if a person reads a backwards leg it should be recorded as a backwards leg eg

5    4    10.34    115    +11

However Sexytopo is just changing the measurements and recording

4   5    10.34    295    -11

This causes 2 problems
If you do not know where the station was read from, you might not be able to go back and check for thinks like magnetic interference or know that it was taken away from the interference, something like a anchor in the wall.
It breaks clino calibration, lets take an extreme example, but one I have seen.

On the above data, if the Clino was reading 4 degrees (something I have seen) under the true reading when the survey program corrects the reading it will then use

5    4    10.34    115    +15 (+11+4)

4   5    10.34    295    -7 ((-11+4)

So the way SexyTopo records the data doubles the error for reversed legs when clino correction is applied. 

There are probably lots of other reasons not to change the readings, but the above are the main 2.

Oh and I have just noticed, it does not actually change the sign of the clino reading, so the reversal of a leg is actually wrong, so the elevation plot becomes wrong

**Comment by richsmith** [comment]
OK, cheers, good explanation. Sounds like this definitely needs changing.

**Comment by richsmith** [comment]
This should now be fixed in the version just released. Inclination problem is fixed, and direction taken on legs is preserved.
