### ISSUE TITLE
Drawing window context menu is blank

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#201]
v1.8.0-beta 1
The context menu is blank
![image](https://github.com/richsmith/sexytopo/assets/19825868/af62b02d-4b47-463b-8887-7f2fa3ea9374)
But if you tap the blank space, the action assigned to that space activates.

Is this perhaps an accident in the dark mode implementation?

**Comment by richsmith** [comment]
Yes! Dark mode bug - should be easy to fix

**Comment by CaverBruce** [comment]
latest update, beta2(?) messed with things on my device.
![image](https://github.com/richsmith/sexytopo/assets/19825868/bd5657bc-30ba-44dc-bc09-f25575088348)

And thereafter ST unresponsive, until App closed.
On reopen, unresponsive blank screen.
Reboot device, same behaviour.

Unsure if random glitch at my end or if the update broke ST beta

**Comment by CaverBruce** [comment]
OK. If seems wait 2 months and it comes right by itself. After trying unsuccessfully to exit beta tester status resulting in not being able to reinstall ST for weeks,  I can now install.  Still beta tester though...
But most importantly I can open existing files.

**Comment by richsmith** [comment]
Fixed in latest beta / version about to be released. Also made loader more tolerant of errors.
