### ISSUE TITLE
New "Text Labels" aren't visible at creation

### ISSUE THREAD

**Issue by rsevero** [richsmith/sexytopo#206]
When a "Text Label" is created, it is not immediatly visible.

Currently I need to change view (to table view for example) and back to plan view to actually see the new text label created.

Expected to see the new text label right after creation without needing to go to another view and back.

Using Sexytopo 1.7.1

**Comment by richsmith** [comment]
Thanks, yes - missing command to invalidate the view. Just fixed, will be included in next full release.

(For now you can just update the view by e.g. moving or drawing or something, and the text should appear).
