### ISSUE TITLE
Therion thconfig "symbol-hide group cave-centreline" prevents vanilla compile

### ISSUE THREAD

**Issue by speleo** [richsmith/sexytopo#215]
The thconfig layout command "symbol-hide group cave-centreline" prevents Therion from being able to compute the size of the map if a user attempts to compile the survey without modification.

Fix: comment out the command

app/src/main/java/org/hwyl/sexytopo/control/io/thirdparty/therion (line 15)
```
-        "  symbol-hide group cave-centreline\n" + 
+        "  #symbol-hide group cave-centreline\n" +
```

**Comment by richsmith** [comment]
Thanks, will push out a fix.
