### ISSUE TITLE
External Storage Access is not handled correctly

### ISSUE THREAD

**Issue by richsmith** [richsmith/sexytopo#29]
Program doesn't properly request permissions (in modern versions of Android) so always ends up falling back to internal storage.

**Comment by CaverBruce** [comment]
Is there a plan to implement functionality similar to PocketTopo, whereby surveys stored in main memory are automatically backed up constantly to a pair of files on a removable card (if present)?  I consider this a necessary feature.
An improvement on that concept would be to implement the reverse as well.  If the user stores surveys on a removable card, ST should constantly back them up to a pair of files in main (non-volatile) memory.

**Comment by richsmith** [comment]
No longer an issue due to file handling changes
