### ISSUE TITLE
Two finger drag to pan

### ISSUE THREAD

**Issue by goatchurchprime** [richsmith/sexytopo#35]
The pinch to zoom works even in drawing mode, so why can't you use the two finger detection here to drag as well as zoom at the same time.  Google maps has it, so it can't be that awful an interface

**Comment by richsmith** [comment]
It's a good idea and I just experimented with adding it but it's fairly difficult to do. I'm using Android's tools to detect pinch-to-zoom and that seems to pick up all multi-finger gestures. Trying to separate out zooms from drags is non-trivial. May look at this again in the future.

**Comment by goatchurchprime** [comment]
Your pinch zoom is already centred in the middle of the line between the two touch points and works in the drawing mode.  If you allow this focus point to be translated to the middle of the two touch points that you have dragged to, then you have the feature.  ie it becomes just part of the pinch-zoom and not a new mode.

**Comment by richsmith** [comment]
I've added this. It's a bit jerky, so I might look at it again and see if I can improve it, but I think it's useful.
