### ISSUE TITLE
Render codewords written as a note as a symbol 

### ISSUE THREAD

**Issue by goatchurchprime** [richsmith/sexytopo#36]
Notes made of letters can be added to any place on the survey.

Why not have special codewords that are plotted as symbols?  

One way would allow for typing up unicode, where we know what the unicode symbol for a stal-curtain is.

Or they could be codewords with a dot in front of them, eg: ".stream" which gets rendered as a stream arrow.

These should have the ability to set the rotation, eg encode in ".stream90" for one that is at 90 degrees.

But if you had a rotation attribute on the general note itself you could stick labels at different angles.

This would be the prequel to inputting cave symbols through a more madphilfriendly interface.

**Comment by richsmith** [comment]
I don't think this is worth it. Few people would find it useful. Think I'll dive straight into adding symbols through a nicer UI.
