### ISSUE TITLE
Cross Section off screen in Therion export

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#42]
The cross section do not appear on the drawing canvas if they are too far off the edge, this can be solved by expanding the area by using numbers in the Drawing Area menu in Xtherion

It would be useful if there was a line joining it to the correct station, also there are no stations in or splays in the import (maybe this should be split into more than one issue)

**Comment by CaverBruce** [comment]
Yes, I noticed this issue on my first trial of SexyTopo

**Comment by AndrewAkinson** [comment]
I've split off the cross section stations, as this is a real pain in drawing up, the going off the screen is not really a problem
Split off issue https://github.com/richsmith/sexytopo/issues/74

**Comment by olly** [comment]
I just ran into this. I had a quick poke around the source code, and I _think_ the root cause is that `SketchDimensions` calculates the dimensions using the legs; whereas I think it should use the min / max coordinates of the paths in the Sketch.

**Comment by richsmith** [comment]
Think I've fixed this in the latest beta version
