### ISSUE TITLE
Comment vanishing

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#44]
I wrote some comments on some stations, however, in the Therion export and now the original files the comments have been replaced by the 3 readings that where taken, it would appear to have overwritten the original comments.

**Comment by richsmith** [comment]
Oops, that's annoying.

I've changed the save file format of SexyTopo to use its own text format. This was to allow saving of directions in extended elevations and other enhanced data. As a result all the saving/loading code has been changed and this bug won't happen again.

There's a small possibility that this bug still exists in the Survex/Therion import but I haven't managed to reproduce it. It definitely seems to export with no problems. I'll close this as a fixed bug.
