### ISSUE TITLE
Numbering and naming of Force New Station

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#48]
Personally I think that this would be better named as Convert to Leg.

When this is done it reverts to the toporobot numbering system 1.1 not the next counting number which would seem more sensible

**Comment by richsmith** [comment]
I agree on the numbering, but I just had a look and this is non-trivial to fix. Will have to remain on backlog for now.

I'm not sure on naming. The thinking behind it was to discourage using it as a matter of course, hence the use of "force". I'm not terribly happy with the phrasing though.

**Comment by AndrewAkinson** [comment]
Maybe Force to leg, ,my main concern was force just was a little ambiguous, force what to do what, which once you are use to it will not be a problem

**Comment by CaverBruce** [comment]
>When this is done it reverts to the toporobot numbering system 1.1 not the next counting number which would seem more sensible
>I agree on the numbering, but I just had a look and this is non-trivial to fix. Will have to remain on backlog for now.

Just musing here, thinking out loud...  All our projects use Therion, and many have multiple numbering systems inherited from legacy practices (paper survey, various numbering conventions, PocketTopo etc) and it works well without being confusing.   Both Therion and the humans handle it well without confusing one input type from the other.
But perhaps consecutive numbers and hierarchical numbering in together as part of the same input type may be a step too far.  At least for those of us used to PocketTopo.  Experimenting with ST, I see that each branch updates the prefix number, ie 1 becomes 1.1 becomes 2.1 becomes 3.1 for three branches off the initial survey of that trip.  In PockeTopo that would look like three series, or the way we have been using it, three separate trips.  One caveat here is that I have not yet tried joining multiple surveys in or from ST.   Perhaps I should do so before commenting further...

**Comment by richsmith** [comment]
"Force new station" doesn't seem to have been a problem so far
