### ISSUE TITLE
Meta data screen

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#49]
Add who was surveying, doing what and what instruments used, auto date. What cave it is in, maybe country, and area Units of instruments, Calibration information about instruments, especially tapes, if a tape is 40cm shorter this is going to effect the drawing. Tapes can be longer and holding the end on is easier than the correct zero (Survex uses the number you read for a 0 length as its datum, so 20 would have the end missing -20 would be longer than it should be) This should also contain a declination box, that is only used to align the drawing screen. Personally I'm not familiar with this as mostly I survey in places where the compass north is very close to grid north, however I have heard that for surveying in places where it is more than 20 degrees out this is useful. (Bruce on the Therion mailing list would be a good person to ask)

**Comment by CaverBruce** [comment]
Ha, you found me!  I just fired up SexyTopo for the first time for ages, and this time it looks like it is getting close to usable.  Yes, metadata like PocketTopo 'actual trip' is required.  Date, declination (to rotate drawing) and free text (preferred) boxes.  In it I write the people, their roles and the instrument and device identifiers.
There is still some work to do, but i can see this will be viable with just a bit more development effort.  I'm excited.  Keep it up

**Comment by richsmith** [comment]
This feature is my next priority. What's most important for this - people in team and role?

**Comment by AndrewAkinson** [comment]
Off the top of my head. In order of importance

Date
Roles: Drawer. Instrument person. Dog (No its not rude)
Instrument used.

A box for general text notes

I've feeling keen a button to say exploring while surveying or add in the
explorer names and date.



Declination. Not used after import to therion/Survex but in areas where it
is tens of degrees this would be good to add to the drawing when doing it.
(If a declination is detected by Survex or Therion they do not add auto
calibrate so it really should not be exported or if it is only as a comment.

Fix point location. Ie entrance point or points. Therion has a way to
define the primary entrance to a system different from all other entrances.

Calibration legs. My first 3 usually. Another option is to be able to
comment out legs. This can then be repeated through the survey. Again
making the order of data important. Actually commenting out and comments is
better.


Andrew

**Comment by CaverBruce** [comment]
I concur with Andrew more or less on all of the above.
Declination is only for rotating the sketch in Sexy Topo and in the exported file formats that parse to therion.  Include a commented out declination statement in the exported survey file, for user information only, as Andrew suggests.

Calibration check of distoX and error detection a la TopoDROID.  This would be desirable, but I suspect it is a big piece of work beyond the scope of this thread.  My current way of checking calibration is 4 spays one way, then 4 splays the other way, and back home this gives slightly more robust data with which to calculate the Therion  calibrate statement parameters than is suggested in the DistoX/PocketTopo guidance.

**Comment by richsmith** [comment]
Currently I've added Trip info: date, team with roles, and comments.

However, in writing the Therion export, is it the case that you can only have one team per survey / centreline? Looks like it, whereas I've added ability to change trip data during survey - argh, could have saved myself some work.

**Comment by olly** [comment]
As far as I know you specify the `team` option in the `centreline` command, but you can have multiple `centreline`s. So perhaps each trip is it's own `centreline`? I think that makes sense as another one of the options is the `date` which would be the trip date.

**Comment by richsmith** [comment]
Makes sense but for now I've restricted it to one trip per survey. Simplifies life quite a lot. Let's see how it goes.

**Comment by CaverBruce** [comment]
It is as Olly says.
With Therion (and with the analogous concepts in PocketTopo, and hopefully SexyTopo) my preference is to treat each SURVEY as a single TRIP (although other users might put multiple trip data within a single survey, if they take a less structured approach).  Throughout the trip, I change the metadata (names/roles/instruments - ie broke the end off the tape for example) as required, and these changes in metadata trigger creation of separate CENTRELINES within the SURVEY

**Comment by richsmith** [comment]
Hopefully SexyTopo users won't be using tapes :P

Having ability to set multiple trip data entries per survey raises a lot of
UI questions - how do you view past trip data, are you you allowed to edit
past trip data that is already linked to survey data, and so on.

For now people can start a new survey chunk for new trips.

**Comment by CaverBruce** [comment]
Had a quick look, and i think what you have done is pretty good for now, subject to a bit of user testing.

PocketTopo has quite a good strategy that is limited, but allows me to do whatever I have ever wanted to do.  Only proviso is that users must put in the metadata before the shot data is uploaded to the device.
ie workflow is;

1.  user enters trip metadata.  This is saved with the app separate to any subsequent or existing shots.
2. shot data is entered/uploaded.  Metadata is now saved to the data file and locked for those shots, users cannot modify it, and cannot see it. They can only see the metadata saved to the app. (it can be seen for previous shots only with exported data and data parsed to likes of Therion)
3. user changes trip metadata when the team, first explorers or instruments change, or the disto is re-calibrated after a knock.
4. more shot data is entered/uploaded.
5. User creates a new file when the passage winds back over itself either in plan or elevation, or a new days survey is started.  The app still retains the trip metadata, so if the team/instruments are the same as the previous trip by default, the user need not change anything.

Uh oh, just noticed there is no declination in the ST trip metadata.
It it the plan to put it in the trip data or is it / has it been placed somewhere else?

**Comment by richsmith** [comment]
I was thinking you could just put declination in the comments. Were you expecting it to actually get processed in SexyTopo? I suppose it might be useful for trips done years apart... does PocketTopo/TopoDroid do this?

**Comment by CaverBruce** [comment]
Hi Rich, yes, centreline and sketch should be rotated by the declination.  Down here in NZ the declination is in excess of 20 degrees, so it makes a significant difference.  It is not to do with variations in declination over time, in-cave software need notextend to such detail.  The reason I want it rotated by the declination (a users rough estimate is sufficient) is so that the sketch and the finished output look roughly the same.  ST needs to produce rotated exports as well of course.  Much easier on the cartographers mental capacity, and it means that Therion drawing object -align statements for the likes of top, bottom, topleft etc are more likely to behave as expected.  As i describe in the Therion wiki, you can also compensate for intentional rotation of the finished cartographed drawing, if you know in advance.  See the third bullet point under CAUTIONS about two thirds of the way down the page https://therion.speleo.sk/wiki/pockettopotherion?s[]=pockettopo&s[]=cautions
and the notes under -align almost half way down this page https://therion.speleo.sk/wiki/drawingchecklist?s[]=rotate#points

Off caving, back in a few days...
