### ISSUE TITLE
thconfig - Therion Export

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#51]
The export pdf are useful, however, -layout local refers to a configuration layout called local, that does not exist in the file, so it will not run. Remove this part is the easiest solution, or add in a layout local  a suggestion would be

layout local
debug off
map-header 0 0 off
#symbol-hide group cave-centreline
endlayout

The export map should also probably be commented out, as they do not work until something is drawn. Usually the first thing a surveyor wants to check is the skeleton view, best created using

export model -fmt survex -o NAMEth.3d

I personally like adding th to the name of my files produced by Therion so I know which program has created them, so if a bug occurs I can work out where.

**Comment by richsmith** [comment]
Done
