### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [richsmith/sexytopo#52]
Hi @richsmith , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by richsmith** [comment]
Hi @zularizal 
Sure, if you're interested in contributing, go for it!
The current logo is a creative commons version of the Danger: laser icon which I'm reasonably happy with but isn't actually personalised to the product.

**Comment by zularizal** [comment]
Hi, this is my design logo for your project.
Previously I have learned about this application. According to what I learned, this application uses a device that can measure a cave with a laser on the device.
Therefore, this logo is inspired by a polyline and a symbol of a mountain and cave (triangle).

What do you think?

If something wants to be changed, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/45337039-5af9ec00-b5b0-11e8-94d2-844f6b4d6aac.png)

**Comment by richsmith** [comment]
Thanks @zularizal!

I like it! It gives the impression of the dual vertical and horizontal nature of cave surveying.

The one thing I'm not so keen on is the colour. Any chance of using the colour #7FAF7F used in the app?

**Comment by zularizal** [comment]
What do you think about this color? I use color #7FAF7F on the line

![bitmap2](https://user-images.githubusercontent.com/38547278/45483542-6c432400-b77b-11e8-8144-d531af84324f.png)

**Comment by richsmith** [comment]
Hi Zularizal.

Looks very good, I like it :)

I would be happy to have that as the icon for SexyTopo.

**Comment by zularizal** [comment]
Hi @richsmith , I have uploaded the logo to the drive in vector format and others. I have also uploaded an icon for Google Play with a size of 512px.

https://drive.google.com/open?id=1nX3_dgNqrE3RFcgQaicW37V5nm-kPSMd

And also I have sent a pull request to you, check this #53

**Comment by richsmith** [comment]
Excellent stuff! I've merged the PR. I don't know if you're a caver at all, but your icons will soon be going into unexplored caves across the world :)

**Comment by richsmith** [comment]
@zularizal , would you like to have your name credited on the About page for logo design? If so, what name should I put?

**Comment by zularizal** [comment]
This logo is open source licensed. You can put my name or not. Because I want to help you.

If you want to enter my name, my name is Zularizal :smile:
