### ISSUE TITLE
Inverse colour (should a dark environment be encountered)

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#54]
Low priority enhancement
A dark theme should be an option, to replace the current light theme.  And like Google maps, there should be the option for it to automatically switch, in response to changing light levels (although head lamps could make this problematic).

**Comment by richsmith** [comment]
Dark theme added. I don't think making it adaptive would be helpful for the reason you point out, though you can tell it to follow the system setting (which is the default) and you could possibly set something on your device to change automatically.
