### ISSUE TITLE
DistoX view should be accessible mid-session

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#55]
The DistoX view with pairing and connection information is an inspired, informative and effective approach.
However once the Table, Plan or Elevation views are activated by the user, there seems to be no way of going back to the DistoX view mid-session.  Taking a punt that connection issues will occur from time to time, it would seem reasonable that the user be able to view the bluetooth and connection status and log.  That would save all sorts of pain and uncertainty that i have experienced with both PocketTopo and TopoDROID.

**Comment by richsmith** [comment]
Oops! That's meant to be a menu item. Looks like I accidentally made it invisible in the last release. Cheers, fixed - update will be released shortly.
