### ISSUE TITLE
Missing root project

### ISSUE THREAD

**Issue by krt16s** [richsmith/sexytopo#6]
It looks like you just pushed the "app" folder into the repo and not the root porject. You most likely have ../build.gradle and ../settings.gradle whcih should be published as well.

**Comment by richsmith** [comment]
Ok, thanks for the info. Will sort it out when I get round to it.

Rich

**Comment by riggsd** [comment]
I'm new to Gradle, but I found that I had to add the following to top of the the module-level `build.gradle` file for it to recognize the `android` plugin:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}
```

It might be more correct for this to be in a top-level `build.gradle` file instead?

**Comment by krt16s** [comment]
It's correct that way or another, but means different things. In one file, it's a single project build. If there are build.gradle and settings.gradle in ../, it's a multiproject build (e.g. the app itself and used libraries). My point is, that you cannot know what repos and deps the buildscript is meant to use without upstream providing that information... Of course you can guess (and getting it right is rather easy most of the time...).

**Comment by krt16s** [comment]
I think 11ee258dc824b40ee5ae5f5c46062011a0941b2a closes this issue.
