### ISSUE TITLE
Therion export - th file has wrong comment character

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#61]
When 3 shots are combined to produce a leg a colon is used to comment out the end of the line, this should be a has.    

1  2  3.89  11.98  -9.83    ;  {from: 3.90 191.98 9.88, 3.89 191.98 9.81, 3.89 191.97 9.81}
should be
1  2  3.89  11.98  -9.83    #  {from: 3.90 191.98 9.88, 3.89 191.98 9.81, 3.89 191.97 9.81}

The alternative is to use ignore all on the end of the data line

    data normal from to length compass clino ignoreall

**Comment by richsmith** [comment]
That's annoying... survex uses the semi colon and the exporters share code

**Comment by AndrewAkinson** [comment]
Tell me about it. The other difference is survex@survex.com uses * before
keywords Therion does not.

Andrew

**Comment by richsmith** [comment]
Fixed on 1.2.3.
