### ISSUE TITLE
therion export - thconfig - no 3d file - will not run without scraps

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#65]
Currently the export commands try to produce a plan and extended elevation, however these are not compilable due to no information in the th2 files. Also the most useful export is a 3d file, therefore I would suggest that the thconfig look something like this, with the plan and extended commented out but ready

source "Bagpit.th"

export model -o Bagpitth.3d

#export map -proj plan -layout local -o "Bagpit-plan.pdf"

#export map -proj extended -layout local -o "Bagpit-ee.pdf"

**Comment by richsmith** [comment]
Done

**Comment by AndrewAkinson** [comment]
Impressive spped
