### ISSUE TITLE
Active station - from sketch accidently selected

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#66]
It appears that tapping on a station in the sketch makes it the active station. This causes problems, if you draw near an previous station it can accidentally become the active station, and it appears that the data is not coming through, (this is related to data order, for which I will open another issue, https://github.com/richsmith/sexytopo/issues/68) and any data that does come through is now connected to the wrong station and cannot be moved to another station (Guess I need to open an issue for this as well https://github.com/richsmith/sexytopo/issues/67)
If a comment is added this also becomes the active station, which is not always useful, I often add previous comments when the team are taking the next readings.
I would suggest that making it an active station is a menu choice.

**Comment by richsmith** [comment]
Hmm, not sure what's going on here. I can't replicate it - for me, only a long press opens the context menu.

However, I have changed things around a bit in the forthcoming release. Opening the context menu (e.g. via long press) no longer sets the station as active. There is now a menu item "Select" that sets the active station. If the menu is accidentally opened, you should be able to click off it.

Let me know if it's still a problem.

**Comment by AndrewAkinson** [comment]
Brilliant. I think that is a better solution. I think I might have been
adding a comment which set them as active.

Andrew
