### ISSUE TITLE
Sketching unresponsive

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#70]
Not actually worked this out yet, so this is really a place holder.

At times when sketching the screen stops responding, sometimes is catches up and draws where the pen has been, at others it is not responding at all, going into move mode and back to drawing seems to help. (this may also happen when moving, but not sure) At times this made it very unusable, I've not seen this when testing at home. It started right at the beginning of the survey, so I doubt it is file size.

At times I think this might be caused by dual touch setting off zoom mode, but at maximum zoom this is hard to tell. Water on the screen might be causing this. I will look into seeing if the galaxy tab can have touch sensitivity turned off so only the pen can be used!

**Comment by richsmith** [comment]
Guessing this may have been SexyTopo autosaving, which is now done asynchronously not on the UI thread, so hopefully no longer an issue. Feel free to reopen if it is.
