### ISSUE TITLE
Sketching colours

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#71]
It would be nice to have grey, I use it lots, mainly for overlapping walls

**Comment by CaverBruce** [comment]
Ah yes, I was almost going to post this myself.
PocketTopo has seven colours; black, grey, brown, blue, red, orange, green
SexyTopo has six colours; black, brown, orange, green, blue, purple

I do miss the grey.  

But the 2x8 control grid at the bottom of the screen is getting quite cluttered - another topic, some of the controls need moving elsewhere on the display - the zoom in/out and undo redo.  They look too much alike and are too close together - always hitting the wrong one.

**Comment by richsmith** [comment]
Added red and grey. Does make it a bit more cluttered - may have to look at your other ticket.
