### ISSUE TITLE
Not working with more than one distoX

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#72]
This might be me just not knowing how to do it. But if 2 distoX are paired it will not connect to the distoX. I had to unpair the other to get it to work

**Comment by CaverBruce** [comment]
Same experience, I decided that this behaviour must be by design for now.

**Comment by richsmith** [comment]
This is by design. It gets especially tricky when having multiple types of instrument attached. No plans to fix, since it would be a lot of effort and it's easy to work around.
