### ISSUE TITLE
Zoom and Undo Redo Controls clutter control grid at bottom of screen

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#77]
The 2x8 control grid at the bottom of the screen is getting quite cluttered - some of the controls need moving elsewhere on the display - the zoom in/out and undo redo for example.  They look too much alike and are too close together for often used controls - always hitting the wrong one.
(Moved this out of #71)

**Comment by richsmith** [comment]
Unlikely to change this, and less of a problem with bigger phone screen. May drop the redo button to the menu if I add another button.
