### ISSUE TITLE
Station naming and the cave survey ecosystem

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#78]
Further to #48 
I have just given v1.1.5 a test run, and think that the default ST station naming/numbering is getting out of hand.
![screenshot_20190120-114159_sexytopo](https://user-images.githubusercontent.com/19825868/51434385-29aecc80-1cc4-11e9-8e83-4942a16a974a.jpg)
The image shows a simple survey with two branches
1 - 2 -3
2 - 2.1 - 2.2
2.1 - 2.1.1 - 2.1.2 -2.1.3
and I have added text labels describing a simpler and more rational scheme
1 - 2 - 3
2 - 4 - 5
4 - 6 - 7 - 8
The cave survey software ecosystem I envisage ST fitting into here includes Therion, Survex, SexyTopo, PocketTopo and probably others.  The first three can handle just about any survey name (I assume) so any scheme works, but Survex's Aven reports PocketTopo's survey.station (ie 1.1, 1.2 etc) numeric format as an extra nested level of survey.  This is just a little quirky, but no harm done, as each PocketTopo survey is always reported by Aven as two levels of survey.  A user can intuitively account for this without too much cognitive load, both in Aven and in Therion outputs.
PocketTopo accepts only numeric survey name and station numbers as I mentioned.

So now ST is less disciplined, and default survey _station_ names can be 'station' or 'station.station' or 'station.station.station' (for how long i do not know).  So there is no benchmark that a user of Survex (Aven) or Therion could use to infer, in a large dataset using various field data formats, to know whether they are looking at one, two, three or more nested levels of survey, unless they go digging into the data in each case.

I have tried manually changing the default ST station names in the file above to the simpler 1 to 8 nomenclature, and ST seems perfectly happy with that.  It also seems happy with alphanumeric names.

I would request/suggest that in the interests of having ST play nicely with other members of the ecosystem, that the default numbering scheme be changed to simply making the next survey station a numeric that is one more than the existing total number of stations in the survey, or if the user has provided a mask/template (say ST01) then ST continue a logical sequence starting from that mask/template (say ST01, ST02, ST03 etc) in much the same way as XTherions Text Editor's data input

**Comment by richsmith** [comment]
Ah, that wasn't quite what I intended!

Your system sounds good and close to what Andrew Atkinson wanted, but I couldn't think of a good way to approach it - the current method is a stopgap.

Maybe I'm overthinking it - is the algorithm as simple as:

* Take the name of the station you're shooting a leg from
* Advance the last digit in the name by 1 (if there's no digit, add a 1)
* If that's not unique in the current survey, keep advancing the number until it is

?

I'll give it a go...

**Comment by richsmith** [comment]
I've fixed this in the new 1.1.5 release.

**Comment by AndrewAkinson** [comment]
Just stick to costing numbers. Everything else just becomes confusing...

Andrew

**Comment by richsmith** [comment]
Assuming that's autocorrect for "counting", it's not quite that simple because people can rename stations to whatever they want... but I think the new approach gives you what you want. If you don't rename anything stations will have single numbers, but otherwise it will try to follow your naming convention.

**Comment by AndrewAkinson** [comment]
Sounds ideal. Should be using it again next week.

Andrew

**Comment by CaverBruce** [comment]
Numbering may now be just about ideal.  Thanks very much (I was getting worried there for a while).
