### ISSUE TITLE
Crash, cannot access data

### ISSUE THREAD

**Issue by cavermax** [richsmith/sexytopo#81]
First in cave run with program. Cannot open files gives (attempt to invoke virtual method java.lang. string org hwyl.sexytopo.model.survey.station.getname()on a null object refrence. Cannot open plan view with any file. Profile view still works.

**Comment by richsmith** [comment]
Thanks for the bug report. I'm not sure what's going on.

The error message is useful but I'm not sure where it's being thrown. Could you please check the system log (under the dev menu) and see if there's a stack trace (more lines related to the error).

When does the error occur? When you first load the file or when you open plan view?

**Comment by cavermax** [comment]
I only get the first error message when I try to open the file tab. When I try to open the plan view I get a black screen lockout for the whole program. If I restart my phone I can open Sexytopo again. Profile and data view are fine.

Chris Caswell
________________________________

**Comment by richsmith** [comment]
I can't work out what the problem might be. Would you be able to send me the file in question (rls@hwyl.org)? And can you confirm you're using the latest version (1.1.6)?

**Comment by cavermax** [comment]
Did you recieve the files? I was not sure if i sent them correctly.

Chris Caswell
________________________________

**Comment by richsmith** [comment]
Perfect, thanks.

I haven't had time to look at them yet - hopefully tomorrow.

cheers
Rich

**Comment by richsmith** [comment]
I've added some code for the upcoming release to sanitise the inputs for station name and survey name, which ought to fix the problem you had.
