### ISSUE TITLE
Therion export incorrect - leg station order

### ISSUE THREAD

**Issue by AndrewAkinson** [richsmith/sexytopo#84]
For some reason although on android the leg is

5 4 4.597 335.26 86.77

The Therion export is 

4  5  4.597  156.26  -86.77    ;  {from: 4.596 335.96 86.82, 4.597 336.34 86.69, 4.597 336.48 86.80}

So he maths comes out the same and it shows what it was calculated from. However, changing data should never be done. The direction of the reading is important. A prime example is when an anchor is use as a station, the leg should always be to the metal, otherwise the compass might be interfered by the metal. This can be checked from the data.
Also on the particular survey I was doing today, I realised that I had got a leg backwards, but checking the therion data is was not. This did confuse me for a while...

**Comment by richsmith** [comment]
Fixed ready for 3.4.2.

(Well it maintains everything as going forward to keep the graph nice, but now exports it so everything points in the direction it's shot in).
