### ISSUE TITLE
Adding a New Cross-Section Causes SexyTopo to Hang

### ISSUE THREAD

**Issue by olly** [richsmith/sexytopo#86]
Trying to adding a "New Cross-Section" causes SexyTopo to hang.

See: https://www.dropbox.com/s/t89w6xj30cq60j1/SexyTopoCrossSectionInputBug.mp4?dl=0

After displaying the text to "Select where to draw cross-section" it seems as if no further input is registered. After waiting for a while the system prompts to close the app as it isn'r responding. This dialog box is also prevented from receiving input, and it's only when opening the app switcher that it's possible to close the dialog.

**Comment by richsmith** [comment]
Thanks for the bug report! The video is useful, but I can't figure out what is going on here. I can't replicate it either.

It's not usual to add a cross section at the origin but SexyTopo should be able to figure something out. Does it work if you do it from a station that is not the origin?

I'm guessing it's caused by a null pointer or something but I can't see where it could have come from. Anything caught in the system log (dev -> System Log)?

**Comment by olly** [comment]
So I thought I was going crazy, as I couldn't initially replicate it either, but I think I've managed it.

1. Select Pen Mode
2. Press down near or on a station, starting to draw a line.
3. Wait for the context menu to appear
4. Select 'New Cross Section'

I'm guessing there's some odd interaction between drawing a line, and then tapping the screen for the cross-section location.

Is there a way to access historical System Logs? As this bug requires the app to be force quit, accessing to log afterwards is empty.

**Comment by richsmith** [comment]
The system log is saved to a file every time it's written to. It should get
reloaded on startup, so if there's nothing in the log then either that's a
separate bug or nothing has been logged. It should write exceptions to the
log before crashing, but it might not if it's just hung.

The file is in something like Documents/SexyTopo/logs or wherever Android
feels like putting it.

The error might have something to do with a change I made the other day in
not automatically setting the station as active if you open the context
menu.

I think that might need a few tweaks...

**Comment by richsmith** [comment]
Haven't really looked at this but I've made a change that may have fixed this.

**Comment by richsmith** [comment]
Looks like system log doesn't reopen when the app gets restarted due to an error (it doesn't call the start up activity when restarted... argh, not sure how to fix that!)

**Comment by richsmith** [comment]
Hopefully fixed the system log issue. I don't know if the hanging is still an issue... Olly?

**Comment by olly** [comment]
Yeah, just checked with the latest version (v1.2.5) and it seems to be fixed. Wasn't able to test the system log reloading (as I couldn't get it to hang).
