### ISSUE TITLE
Terminology needs to be consistent; select vs set active station

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#89]
Tried using ST in a simulated real survey scenario for the first time over the weekend. And took the opportunity to start training a friend in the principles of paperless surveying (using ST v1.2.2).
In the data table view, 'tap and holding' a station brings up a menu with the option 'Set Active Station'.
In the drawing views, 'tap and holding' a station brings up a menu with the option 'Select'.
As far as I can tell, both these activities achieve the same thing, ie setting the active station from which the next legs or splays will be attached.  If that is the case then the terminology should be identical.

**Comment by richsmith** [comment]
Fixed
