### ISSUE TITLE
Identify and go to corresponding view of station

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#91]
Once a survey becomes more than trivial, it is often necessary to navigate easily between the table, plan and elevation views, of a particular station, or identify the graphical view of a particular leg, that may not necessarily be the active station.  PocketTopo does it with the three bottom context menu items as below.  From the data table it simply navigates to the appropriate view and places the selected station dead centre of screen.

![PocketTopo Goto Menu](https://user-images.githubusercontent.com/19825868/55266855-e1bfad80-52e3-11e9-9cac-8de749f448fc.png)

For stations, it can move you between any of the views.
For splays, it can move you from the table to identify particular splay shots in plan or elevation, but not the other way around (but that would be a nice feature - I regularly want to identify an errant splay that I can see graphically, but not find in the table).

This is an important feature for any in cave sketching I think.

**Comment by CaverBruce** [comment]
As an afterthought, one thing that some navigation apps have is a small + at dead centre of screen.  PocketTopo does not have this, and so when the survey is very dense, it is not always clear which of the 12 stations is dead centre of screen.  A small black thin lined + centre of screen would be one way of solving this.

Alternatively the identified station could be coloured differently to the 'active/selected' (yellow) station in both the table and graphic views.

**Comment by richsmith** [comment]
Yeah this would be useful, and easy enough to add I think (at least moving to the station in view, not sure about the table).

**Comment by tomfoord** [comment]
I'd also be keen to have the features described by Bruce, along with the ability to navigate directly from the sketches to a specific station in the data (preferably via an option in the station context menu). Currently it's bit of a pain having to scroll all the way through the data table to try and find the station I'm interested in, particularly for a big survey.

**Comment by richsmith** [comment]
OK, added some basic jumping between stations using context menus in the next version. Can be made better but this is for basic testing.

BTW figure you've both gained a credit in the "about" file... assuming you get to use it in the Dachstein Tom :stuck_out_tongue:
