### ISSUE TITLE
hot corners need extent indication

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#94]
The hot corners introduced recently are a nice feature.
However there is no visual que that they are active, nor how big the 'hot drag' area is.
Suggest adding an transparent shaded or outlined area in each hot corner, when they are active and able to be used.

**Comment by richsmith** [comment]
Ah yes, should be easy enough.

**Comment by richsmith** [comment]
This turns out to be slightly trickier than anticipated as it conflicts with the current position of the legend. Legend either needs moving when they're active or only 3 corners should get the indicator, or something else!

**Comment by CaverBruce** [comment]
Three corners would be a good start, to test and refine the concept.

**Comment by richsmith** [comment]
Oh go on then, I've given it a go. In the new 1.3.4.

**Comment by CaverBruce** [comment]
Excellent implementation.  I especially like the yellow highlight when the hot corner is activated.
