### ISSUE TITLE
xvi coordinates reflected about x axis in plan and elevation

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#95]
v1.3.0 exporting to Therion.  The xvi sketches for plan and elevation are reflected about the x axis.  *.th and pockettopo *.txt export seem to be OK, i think it is just the calculated coordinates for xvi.
Attached are simple plan and elevation doodles to illustrate.  the sketches are faithful to the ST file, but the xvi centrelines are reflected. 
![image](https://user-images.githubusercontent.com/19825868/59096305-a76f2e00-896e-11e9-94be-2225b6535364.png)
![image](https://user-images.githubusercontent.com/19825868/59096337-b81fa400-896e-11e9-83e3-489b201701e4.png)

**Comment by richsmith** [comment]
Aargh! Thought I'd checked all the code that did this. Easy to fix but a bit of a show-stopper. I'll try to fix sometime this weekend.

**Comment by richsmith** [comment]
Fixed
