### ISSUE TITLE
PocketTopo export date is incorrect

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#96]
PocketTopo export dates are always 1970 I think.
The Therion export is correct however.
![image](https://user-images.githubusercontent.com/19825868/59096593-4b58d980-896f-11e9-93c0-de0b4cd68b10.png)
![image](https://user-images.githubusercontent.com/19825868/59096634-688da800-896f-11e9-9706-7ee7a0ccfeb4.png)

**Comment by richsmith** [comment]
Fixed
