### ISSUE TITLE
SexyTopo data files not visible when phone plugged into windows 10

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#97]
I have a simple Nokia II phone that I've been using to try SexyTopo in real cave survey exercise.
Several game stopping issues with the ST data table (more on those later) have become apparent in the cave, and now I'm trying to patch what we did get into the main Therion dataset.  I'm having trouble extracting the files from the phone and getting them onto my Windows 10 machine.
The SexyTopo files are stored in the phones documents folder, and this along with the calibrations, logs, exported, surveys and 'to import' folders are visible with Windows 10 Explorer.  Trouble is, only some of the survey, exported ptopo-txt and exported Therion files are visible in Windows 10.  All expected files are visible on the phones storage app.
It seems like that if the files have been there long enough, I can see them with Win 10, but that does not always seem to be the case.   Sometimes if i copy the files to the downloads folder, they are all visible, but other times they are not visible, or only some of the contents are visible.
So I seem to be stuck with the files on the phone, not easily able to get them out, unless i copy them by selecting the contents of each subfolder and bluetooth transferring them.  Way too tedious and (user) error prone for me.  Should be able to just plug phone onto computer, select folders and copy the lot.

Maybe related to #29 ?
Maybe just an issue with the Nokia II software or hardware, or some Android characteristic I'm not familiar with.

**Comment by richsmith** [comment]
This seems to be a pretty commmon problem with some combinations of Android hardware / drivers / access software. Annoying, but I don't think this anything to do with SexyTopo.
