### ISSUE TITLE
Current Trip export to Therion .th formatting

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#98]
Just a very minor quibble regarding 'Current Trip' formatting...
Currently it places the current trip comment as a separated 'block' of text prior to the main 'current trip' metadata.
```
	centreline
	
		# survey camp leval
		
		date 2019.06.14
		team "Joe Holden" notes
		team "Joe Mutton" instruments
```
I would prefer if it were formatted to be clearly related to the 'current trip' metadata, like this;
```
	centreline
	
		date 2019.06.14
		# survey camp leval
		team "Joe Holden" notes
		team "Joe Mutton" instruments
```
or like this;
```
	centreline
	
		date 2019.06.14
		team "Joe Holden" notes
		team "Joe Mutton" instruments
		# survey camp leval
```

**Comment by richsmith** [comment]
Fixed in forthcoming 1.3.4.
